include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - test/**.mocks.dart
    - lib/generated_plugin_registrant.dart
  strong-mode:
    implicit-casts: false
  errors:
    avoid_equals_and_hash_code_on_mutable_classes: error
    missing_required_param: error
    unrelated_type_equality_checks: error
    conditional_uri_does_not_exist: error
    always_declare_return_types: warning
    avoid_js_rounded_ints: warning
    avoid_unnecessary_containers: warning
    avoid_void_async: warning
    cancel_subscriptions: warning
    close_sinks: warning
    missing_return: warning
    noop_primitive_operations: warning
    parameter_assignments: warning
    prefer_final_in_for_each: warning
    prefer_mixin: warning
    unawaited_futures: warning
    unnecessary_await_in_return: warning
    unnecessary_null_aware_assignments: warning
    use_if_null_to_convert_nulls_to_bools: warning
    use_string_buffers: warning

linter:
  rules:
    - always_declare_return_types
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - conditional_uri_does_not_exist
    - directives_ordering
    - noop_primitive_operations
    - only_throw_errors
    - parameter_assignments
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_interpolation_to_compose_strings
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - sized_box_shrink_expand
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_to_list_in_spreads
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_string_buffers
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
