name: smart_banner
description: Display a smart banner on top of the screen of your Flutter Web application.
version: 0.0.1
homepage: https://github.com/TesteurManiak/smart_banner

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.7

dev_dependencies:
  alchemist: ^0.5.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
